export const strings = {
  app: {
    title: "Household Book",
    defaultWallet: "Main Wallet",
  },
  common: {
    add: "Add",
    amount: "Amount",
    cancel: "Cancel",
    close: "Close",
    comment: "Comment",
    create: "Create",
    date: "Date",
    delete: "Delete",
    noData: "No data",
    save: "Save",
    store: "Store",
    total: "Total",
  },
  home: {
    archive: "Archive",
    annualSavings: "Annual Savings",
    budgets: "Budgets",
    expenses: "Expenses",
    expenditure: "Expenditure",
    goalComment: "Goal Comment",
    monthlySummary: "Monthly Summary",
    noGoalComment: "No goal comment",
    portKeys: "Port Keys",
    remaining: "Remaining",
    savings: "Savings",
    shoppingList: "Shopping List",
    totalSavings: "Total Savings",
  },
  portKeys: {
    all: "All",
    allEntries: "All Entries",
    amount: "Amount",
    bankDeposit: "Deposit",
    bankWithdrawal: "Withdrawal",
    dailyGoodsItems: "Daily Goods Items",
    description: "Description",
    electricity: "Electricity",
    event: "Event",
    fixedInternet: "Internet",
    fixedRent: "Rent",
    foodItem: "Item",
    goalComment: "Goal Comment",
    historySuffix: "Entries",
    input: "Input",
    item: "Item",
    manageItems: "Manage items",
    monthlyBudget: "Monthly Budget",
    monthlySpendingGoal: "Monthly spending goal",
    result: "Result",
    saveBudget: "Save Budget",
    saveFixed: "Save Fixed",
    type: "Type",
    variableGas: "Gas",
    variableWater: "Water",
  },
  reports: {
    annualReport: "Annual Report",
    breakdown: "Breakdown",
    category: "Category",
    categoryTotals: "Category Totals",
    dailyGoodsStack: "Daily Goods Stack",
    deleteData: "Delete Data",
    exportAnnualPdf: "Export Annual PDF",
    exportPdfAndClose: "Export PDF and Close",
    foodTrend: "Food Trend",
    monthlyCloseReport: "Monthly Close Report",
    monthlyComments: "Monthly Comments",
    monthlyReports: "Monthly Reports",
    portKey: "Port Key",
    saveComment: "Save Comment",
    startNewYear: "Start New Year",
    totalBudgets: "Total Budgets",
    totalExpenses: "Total Expenses",
  },
  shopping: {
    dailyGoods: "Daily Goods",
    food: "Food",
    foodItem: "Food Item",
    lineSendQueued: "LINE send queued",
    pending: "Pending",
    scheduledSend: "Scheduled Send",
    sendToLine: "Send to LINE",
    shoppingList: "Shopping List",
  },
  wallets: {
    addWallet: "Add Wallet",
    walletActions: "Wallet actions",
    walletName: "Wallet Name",
    wallets: "Wallets",
  },
  toast: {
    actionFired: "Mock action fired",
    added: "Added",
    commentSaved: "Comment saved",
    deleted: "Deleted",
    itemAdded: "Item added",
    saved: "Saved",
    scheduledDisabled: "Scheduled send disabled",
    scheduledEnabled: "Scheduled send enabled",
    walletCreated: "Wallet created",
    walletDeleted: "Wallet deleted",
    walletSelected: "Wallet selected",
  },
}
