export const actionRegistry = [
  {
    uid: "ACT-0101",
    key: "navigateScreen",
    label: "Navigate screen",
    description: "サイドバーまたは画面内ショートカットから別のSPAルートを開く。",
    triggerComponentUid: "CMP-0005",
    screenUid: "APP",
    status: "mock",
    note: "Updates location.hash only.",
  },
  {
    uid: "ACT-0102",
    key: "selectPortKeyCategory",
    label: "Select Port Key category",
    description: "ポートキー画面を開き、対象カテゴリのタブを選択する。",
    triggerComponentUid: "CMP-0202",
    screenUid: "SCR-0002",
    status: "mock",
    note: "Updates in-memory mock state only.",
  },
  {
    uid: "ACT-0103",
    key: "selectReportMonth",
    label: "Select report month",
    description: "記録済みの月を選択し、レポート画面を開く。",
    triggerComponentUid: "CMP-0302",
    screenUid: "SCR-0003",
    status: "mock",
    note: "Updates selectedMonth in memory only.",
  },
  {
    uid: "ACT-0200",
    key: "changeInputDate",
    label: "Change input date",
    description: "ポートキー入力フォームで共通利用する入力日を変更する。",
    triggerComponentUid: "CMP-0203",
    screenUid: "SCR-0002",
    status: "mock",
    note: "Updates selectedMonth and inputDate in memory only.",
  },
  {
    uid: "ACT-0201",
    key: "saveBudget",
    label: "Save budget",
    description: "月次予算額と目標コメントを保存する。",
    triggerComponentUid: "CMP-0211",
    screenUid: "SCR-0002",
    status: "mock",
    note: "No API call. Updates mock wallet entries in memory.",
  },
  {
    uid: "ACT-0202",
    key: "addBankEntry",
    label: "Add Bank entry",
    description: "銀行の入金または出金明細を追加する。",
    triggerComponentUid: "CMP-0213",
    screenUid: "SCR-0002",
    status: "mock",
    note: "No persistence. Adds an in-memory entry.",
  },
  {
    uid: "ACT-0203",
    key: "addFoodEntry",
    label: "Add Food entry",
    description: "食費の支出明細を追加する。",
    triggerComponentUid: "CMP-0215",
    screenUid: "SCR-0002",
    status: "mock",
    note: "No persistence. Adds an in-memory entry.",
  },
  {
    uid: "ACT-0204",
    key: "addDailyGoodsEntry",
    label: "Add Daily Goods entry",
    description: "日用品の支出明細を追加する。",
    triggerComponentUid: "CMP-0217",
    screenUid: "SCR-0002",
    status: "mock",
    note: "No persistence. Adds an in-memory entry.",
  },
  {
    uid: "ACT-0205",
    key: "openDailyGoodsItemDialog",
    label: "Open Daily Goods item dialog",
    description: "日用品マスタ管理ダイアログを開く。",
    triggerComponentUid: "CMP-0219",
    screenUid: "SCR-0002",
    status: "mock",
    note: "Uses native dialog where available.",
  },
  {
    uid: "ACT-0206",
    key: "addDailyGoodsMasterItem",
    label: "Add Daily Goods master item",
    description: "選択可能な日用品マスタ項目を追加する。",
    triggerComponentUid: "CMP-0218",
    screenUid: "SCR-0002",
    status: "mock",
    note: "Updates mock wallet householdItems in memory.",
  },
  {
    uid: "ACT-0207",
    key: "deleteDailyGoodsMasterItem",
    label: "Delete Daily Goods master item",
    description: "日用品マスタ項目を選択肢から非表示にする。",
    triggerComponentUid: "CMP-0218",
    screenUid: "SCR-0002",
    status: "mock",
    note: "Mock logical delete in memory.",
  },
  {
    uid: "ACT-0208",
    key: "addSpecialEntry",
    label: "Add Special entry",
    description: "特別費の支出明細を追加する。",
    triggerComponentUid: "CMP-0221",
    screenUid: "SCR-0002",
    status: "mock",
    note: "No persistence. Adds an in-memory entry.",
  },
  {
    uid: "ACT-0209",
    key: "saveFixedCosts",
    label: "Save Fixed costs",
    description: "家賃とインターネット料金の固定費設定を保存する。",
    triggerComponentUid: "CMP-0223",
    screenUid: "SCR-0002",
    status: "mock",
    note: "Updates mock wallet fixedSettings in memory.",
  },
  {
    uid: "ACT-0210",
    key: "addVariableCosts",
    label: "Add Variable costs",
    description: "電気、ガス、水道の変動費明細を追加する。",
    triggerComponentUid: "CMP-0225",
    screenUid: "SCR-0002",
    status: "mock",
    note: "No persistence. Adds in-memory entries for amounts greater than zero.",
  },
  {
    uid: "ACT-0211",
    key: "deleteCurrentMonthEntry",
    label: "Delete current-month entry",
    description: "表示中の月の履歴テーブルから明細を削除する。",
    triggerComponentUid: "CMP-0231",
    screenUid: "SCR-0002",
    status: "mock",
    note: "Removes the in-memory entry only.",
  },
  {
    uid: "ACT-0301",
    key: "saveMonthlyComment",
    label: "Save monthly comment",
    description: "月次締めレポートのコメントを保存する。",
    triggerComponentUid: "CMP-0316",
    screenUid: "SCR-0003",
    status: "mock",
    note: "Updates monthlyComment in memory only.",
  },
  {
    uid: "ACT-0302",
    key: "exportMonthlyReportMock",
    label: "Export monthly report",
    description: "月次PDF出力と締め処理のMockを実行する。",
    triggerComponentUid: "CMP-0315",
    screenUid: "SCR-0003",
    status: "mock",
    note: "No real PDF output.",
  },
  {
    uid: "ACT-0303",
    key: "editAnnualComment",
    label: "Edit annual comment",
    description: "年間レポート内の月別コメントを編集する。",
    triggerComponentUid: "CMP-0324",
    screenUid: "SCR-0003",
    status: "mock",
    note: "Updates annualRecords in memory only.",
  },
  {
    uid: "ACT-0304",
    key: "exportAnnualReportMock",
    label: "Export annual report",
    description: "年間PDF出力のMockを実行する。",
    triggerComponentUid: "CMP-0325",
    screenUid: "SCR-0003",
    status: "mock",
    note: "No real PDF output.",
  },
  {
    uid: "ACT-0305",
    key: "deleteYearMock",
    label: "Delete year data",
    description: "年次データ削除のMockを実行する。",
    triggerComponentUid: "CMP-0326",
    screenUid: "SCR-0003",
    status: "mock",
    note: "Does not delete persisted data because there is no persistence.",
  },
  {
    uid: "ACT-0306",
    key: "startNewFiscalYearMock",
    label: "Start new fiscal year",
    description: "新年度開始処理のMockを実行する。",
    triggerComponentUid: "CMP-0327",
    screenUid: "SCR-0003",
    status: "mock",
    note: "Updates fiscal year fields in memory only.",
  },
  {
    uid: "ACT-0401",
    key: "addShoppingFood",
    label: "Add shopping Food item",
    description: "買い物リストに食材項目を追加する。",
    triggerComponentUid: "CMP-0402",
    screenUid: "SCR-0004",
    status: "mock",
    note: "Adds an in-memory shopping item.",
  },
  {
    uid: "ACT-0402",
    key: "addShoppingDailyGoods",
    label: "Add shopping Daily Goods item",
    description: "買い物リストに日用品項目を追加する。",
    triggerComponentUid: "CMP-0404",
    screenUid: "SCR-0004",
    status: "mock",
    note: "Adds an in-memory shopping item.",
  },
  {
    uid: "ACT-0403",
    key: "toggleLineSchedule",
    label: "Toggle scheduled LINE send",
    description: "定期LINE送信の有効、無効を切り替える。",
    triggerComponentUid: "CMP-0411",
    screenUid: "SCR-0004",
    status: "mock",
    note: "No LINE integration.",
  },
  {
    uid: "ACT-0404",
    key: "sendLineMock",
    label: "Send to LINE",
    description: "未完了の買い物項目をLINEへ送信するMockを実行する。",
    triggerComponentUid: "CMP-0412",
    screenUid: "SCR-0004",
    status: "mock",
    note: "No LINE integration.",
  },
  {
    uid: "ACT-0405",
    key: "toggleShoppingDone",
    label: "Toggle shopping item done",
    description: "買い物項目の完了、未完了を切り替える。",
    triggerComponentUid: "CMP-0414",
    screenUid: "SCR-0004",
    status: "mock",
    note: "Updates in-memory shopping item state.",
  },
  {
    uid: "ACT-0406",
    key: "deleteShoppingItem",
    label: "Delete shopping item",
    description: "買い物項目を削除する。",
    triggerComponentUid: "CMP-0415",
    screenUid: "SCR-0004",
    status: "mock",
    note: "Deletes an in-memory shopping item only.",
  },
  {
    uid: "ACT-0501",
    key: "selectWallet",
    label: "Select wallet",
    description: "現在利用するお財布を切り替える。",
    triggerComponentUid: "CMP-0505",
    screenUid: "SCR-0005",
    status: "mock",
    note: "Updates currentWalletId in memory only.",
  },
  {
    uid: "ACT-0502",
    key: "openWalletDialog",
    label: "Open wallet dialog",
    description: "お財布追加ダイアログを開く。",
    triggerComponentUid: "CMP-0502",
    screenUid: "SCR-0005",
    status: "mock",
    note: "Uses native dialog where available.",
  },
  {
    uid: "ACT-0503",
    key: "createWalletMock",
    label: "Create wallet",
    description: "モックのお財布を作成する。",
    triggerComponentUid: "CMP-0509",
    screenUid: "SCR-0005",
    status: "mock",
    note: "Adds an in-memory wallet only.",
  },
  {
    uid: "ACT-0504",
    key: "deleteWalletMock",
    label: "Delete wallet",
    description: "お財布を論理削除する。",
    triggerComponentUid: "CMP-0507",
    screenUid: "SCR-0005",
    status: "mock",
    note: "Marks a mock wallet deleted in memory only.",
  },
]
